// react/umi3/src/pages/home/index.js
/*
 * @Author: zzj
 * @Date: 2021-06-16 14:43:51
 * @LastEditors: zzj
 * @LastEditTime: 2021-06-21 10:44:09
 * @Description:
 */
import React from 'react';
import Header from './components/header';
import Hot from './components/hot';
import Search from './components/search';

import './index.less';

export default function (props) {
  return (
    <div className="home">
      {/* 登录 */}
      <Header />
      {/* 搜索 */}
      <Search />
      {/* 热门民宿 */}
      <Hot />
    </div>
  );
}

// vuejs/front/src/views/Home.vue
<!--
 * @Author: zzj
 * @Date: 2020-11-16 20:40:28
 * @LastEditors: zzj
 * @LastEditTime: 2020-11-17 14:11:04
 * @Description: 
-->
<template>
  <div>
    <panel></panel>
    <router-view></router-view>
  </div>
</template>

<script>
import Panel from "@/components/Panel";

export default {
  name: "home",
  components: {
    Panel,
  },
};
</script>

<style lang="scss" scoped>
</style>
