// react/react_admin/src/page/home/index.js
/*
 * @Author: zzj
 * @Date: 2020-12-15 17:21:37
 * @LastEditors: zzj
 * @LastEditTime: 2020-12-15 17:47:30
 * @Description:
 */
import React, { Component } from "react";
import { DatePicker } from "antd";

class Home extends Component {
  render() {
    return (
      <div>
        <DatePicker></DatePicker>
      </div>
    );
  }
}

export default Home;

// vuejs/front/src/views/Home.vue
<!--
 * @Author: zzj
 * @Date: 2020-11-16 20:40:28
 * @LastEditors: zzj
 * @LastEditTime: 2020-11-17 14:11:04
 * @Description: 
-->
<template>
  <div>
    <panel></panel>
    <router-view></router-view>
  </div>
</template>

<script>
import Panel from "@/components/Panel";

export default {
  name: "home",
  components: {
    Panel,
  },
};
</script>

<style lang="scss" scoped>
</style>
