// vuejs/front/src/views/User.vue
<!--
 * @Author: zzj
 * @Date: 2020-11-26 10:34:58
 * @LastEditors: zzj
 * @LastEditTime: 2020-11-26 10:35:29
 * @Description: 
-->
<template>
  <div>用户的个人首页</div>
</template>

<script>
export default {
  name: "home",
  components: {},
  data() {
    return {};
  },
  computed: {},
  watch: {},
  //生命周期 - 创建完成（可以访问当前this实例）
  created() {},
  //生命周期 - 挂载完成（可以访问DOM元素）
  mounted() {},
  methods: {},
};
</script>
<style lang='scss' scoped>
</style>

// react/umi3/src/pages/function/context/user.js
/*
 * @Author: zzj
 * @Date: 2021-05-18 21:49:42
 * @LastEditors: zzj
 * @LastEditTime: 2021-05-18 22:10:38
 * @Description:
 */
import React, { useState, useEffect, useContext } from 'react';
import { UserContext } from './userContext';

export default function (props) {
  // const [count, setCount] = useState(0);
  const { state } = useContext(UserContext);

  useEffect(() => {}, []);

  return (
    <div>
      <h1>user:</h1>
      <h1>user-id:{state.user.id}</h1>
      <h1>user-name:{state.user.name}</h1>
    </div>
  );
}
