// vuejs/front/src/views/Home.vue
<!--
 * @Author: zzj
 * @Date: 2020-11-16 20:40:28
 * @LastEditors: zzj
 * @LastEditTime: 2020-11-17 14:11:04
 * @Description: 
-->
<template>
  <div>
    <panel></panel>
    <router-view></router-view>
  </div>
</template>

<script>
import Panel from "@/components/Panel";

export default {
  name: "home",
  components: {
    Panel,
  },
};
</script>

<style lang="scss" scoped>
</style>

// react/react_bike/src/pages/home/index.js
/*
 * @Author: zzj
 * @Date: 2021-01-23 21:28:57
 * @LastEditors: zzj
 * @LastEditTime: 2021-01-23 21:30:51
 * @Description:
 */
import React from "react";
import "./index.less";

class Home extends React.Component {
  render() {
    return <div className="home-wrap">后台管理系统</div>;
  }
}

export default Home;
