// webapp/mint-demo/src/views/Home.vue
<!--
 * @Author: zzj
 * @Date: 2021-03-30 16:39:35
 * @LastEditors: zzj
 * @LastEditTime: 2021-03-31 22:02:40
 * @Description: 
-->
<template>
  <div class="home">
    <mt-cell title="标题文字"></mt-cell>
    <mt-cell title="标题文字" value="说明文字"></mt-cell>
  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: "Home",
  components: {},
};
</script>

// react/react_admin/src/page/home/index.js
/*
 * @Author: zzj
 * @Date: 2020-12-15 17:21:37
 * @LastEditors: zzj
 * @LastEditTime: 2020-12-15 17:47:30
 * @Description:
 */
import React, { Component } from "react";
import { DatePicker } from "antd";

class Home extends Component {
  render() {
    return (
      <div>
        <DatePicker></DatePicker>
      </div>
    );
  }
}

export default Home;
