// ssr/nuxt-demo/pages/list.vue
<!--
 * @Author: zzj
 * @Date: 2021-03-27 17:10:50
 * @LastEditors: zzj
 * @LastEditTime: 2021-03-27 17:11:00
 * @Description: 
-->
<template>
  <div>list</div>
</template>

<script>
export default {
  name: 'List',
  components: {},
  data() {
    return {}
  },
  computed: {},
  watch: {},
  // 生命周期 - 创建完成（可以访问当前this实例）
  created() {},
  // 生命周期 - 挂载完成（可以访问DOM元素）
  mounted() {},
  methods: {},
}
</script>
<style lang="scss" scoped></style>

// react/train-ticket/src/query/List.js
/*
 * @Author: zzj
 * @Date: 2021-04-24 15:46:44
 * @LastEditors: zzj
 * @LastEditTime: 2021-04-24 15:47:39
 * @Description:
 */
import React from "react";
import "./List.css";
import PropTypes from "prop-types";

export default function List(props) {
  return <div></div>;
}

List.propTypes = {
  time: PropTypes.number.isRequired,
};
