// react/umi3/src/pages/home/index.js
/*
 * @Author: zzj
 * @Date: 2021-06-16 14:43:51
 * @LastEditors: zzj
 * @LastEditTime: 2021-06-21 10:44:09
 * @Description:
 */
import React from 'react';
import Header from './components/header';
import Hot from './components/hot';
import Search from './components/search';

import './index.less';

export default function (props) {
  return (
    <div className="home">
      {/* 登录 */}
      <Header />
      {/* 搜索 */}
      <Search />
      {/* 热门民宿 */}
      <Hot />
    </div>
  );
}

// vuejs/mutao/src/pages/home/index.vue
/**
* @name: index
* @author: 张中俊
* @date: 2020/6/3 16:25
* @description：index
* @update: 2020/6/3 16:25
*/
<template>
    <div class="home">
        <header class="g-header-container">
            <home-header></home-header>
        </header>
        <div>
            <home-slider></home-slider>
        </div>
        <div class="g-backtop-container"></div>
        <router-view></router-view>
    </div>
</template>

<script>
  import HomeHeader from './header';
  import HomeSlider from './slider';
  export default {
    name: 'index',
    components: {
      HomeHeader,
      HomeSlider
    }
  };
</script>

<style scoped>

</style>
